version: "3.9"

services:
  backend-php74:
    build:
      context: .
      dockerfile: dockerfiles/oel7-php74.dockerfile
    ports:
      - 80-85:80
      - 443-448:443
    scale: 6
    volumes:
      - /var/svn/${SVN_FOLDER}/html:/var/www/html
      - /var/svn/${SVN_FOLDER}/inc:/var/www/inc
      - /var/svn/${SVN_FOLDER}/script:/var/www/script
      - /var/svn/${SVN_FOLDER}/conf:/var/www/conf
    environment:
      - SERVERNAME=wac74.kmu.edu.tw
    command: /run.sh

